[build]
  publish = "public"
  command = "node --max_old_space_size=4096 ./node_modules/.bin/gatsby build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
